### ISSUE TITLE
Load subentities with JPQL/EntitGraph is not working

### ISSUE THREAD

**Issue by MelleD** [eclipse-ee4j/eclipselink#1052]
With a EntityGraph or JPQL it is not possible to load subentities. The sub entities are loaded in extra selects. Example:

```
@NamedEntityGraph( name = "All",
                   attributeNodes = {
                         @NamedAttributeNode( value = "bars", subgraph = "subgraph.foobars") },
                         subgraphs = {
                         @NamedSubgraph( name = "subgraph.foobars",
                                         attributeNodes = {
                                               @NamedAttributeNode(value = "fooBars", subgraph = "subgraph.foobar"),
                                               @NamedAttributeNode( "mqttEndpoints" ) } ),
                         @NamedSubgraph( name = "subgraph.foobar",
                                         attributeNodes = {
                                               @NamedAttributeNode( "name" ) } ) })

public class Foo {
   @OneToMany( fetch = FetchType.LAZY )
   private Set<Bar> bars = Sets.newHashSet();
}

public class Bar {
   @OneToMany( fetch = FetchType.LAZY )
   private Set<FooBar> fooBars = Sets.newHashSet();
}

public class FooBar {
   String name;
}

```

Use EntityGraph or JPQL is not working

```
"SELECT DISTINCT f FROM foo f"
                 + " LEFT JOIN FETCH f.bar bars "
                 + " LEFT JOIN FETCH bars.fooBars foobars "
                 + " WHERE t.id =:id " )

```

Log is 2 selects instead of 1

```
SELECT ...
FROM foo t1 
LEFT OUTER JOIN bars t0 ON (t0.bar_id = t1.id) 


SELECT name
FROM foobar 
WHERE ...
```

**Comment by AleksNo** [comment]
Hi, what outcome do you expect?

Cheers

**Comment by MelleD** [comment]
@AleksNo thanks for the quick reply. I would expect 1 Select with a additional LEFT OUTER JOIN to foobar.
The second select is not necessary. 
If i use the QueryHint https://www.eclipse.org/eclipselink/documentation/2.5/jpa/extensions/q_left-join-fetch.htm this works with 1 SELECT, so this should also work with Query and EntityGraph

**Comment by AleksNo** [comment]
Hi, i have read the Jakarta Persistence Api Pdf:
https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.pdf

And there are no requirements to fetch an EntityGraph in one query. So Eclipselink does nothing wrong. I guess this "select n+1"-fetching is intentional because it works very well with the caching mechanism. If you fetch the data via (left) joins then this would completely bypass the cache.

Cheers

**Comment by MelleD** [comment]
The question is what is the difference between not loading the subgraph and loading the first graph?

In addition, I would expect if I write a JPQL query myself that the JOINS will be evaluated and not simply ignored.

And that EclipseLink can load sub entities it is shown via QueryHint. This works fine.

**Comment by MelleD** [comment]
@AleksNo I think you are right about EntityGraph, it is not specified exactly how the data is loaded, but for JPQL the how is specified directly in the query.

It looks a bit complicated to write such a query over QueryHints.

**Comment by MelleD** [comment]
@AleksNo What is the difference to my SELECT?
Either JPQL or Entity Graph, of course. I've only tried both and haven't been successful.
In summary, QueryHints work great. EntityGraph and JQPL do not work with subentities.

The SPEC does not exactly describe how EntityGraph should load.
I'm still unsure about JPQL. What the spec defines. I found some stackoverflow posts, who say that subentities with JPQL are not in the SPEC.

**Comment by MelleD** [comment]
But with QueryHints there are a few restrictions with the EntityManager.

**Comment by AleksNo** [comment]
Hi, the difference in my SQL statement is "LEFT JOIN FETCH f.bar<span style="color:red">s</span> bars" instead of "LEFT JOIN FETCH f.bar bars". Maybe the forgotten 's' is causing the trouble.

And as i wrote you do not need EntityGraphs when you use the JOIN FETCH statement because it is almost the same functionality. EntityGraphs are way more useful when you use the Criteria API. Before the EntityGraphs were introduced there was no easy way to define a **reusable** fetch plan.

Cheers.

**Comment by MelleD** [comment]
According to this article https://stackoverflow.com/questions/66765679/load-subentities-with-jpql-entitgraph-is-not-working-with-eclipselink-and-spring/66817987?noredirect=1#comment118274697_66817987, an entity graph does not say how a graph is loaded and withJ PQL no subentities are possible
