### ISSUE TITLE
PostgreSQL new error being logged on EclipseLink 4.0.0

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1668]
Running with PostgreSQL + EclipseLink 4.0.0, I am seeing a new log message

```
[8/23/22, 15:20:52:524 CDT] 0000003a eclipselink                                                  I CWWJP9990I: [eclipselink] EclipseLink, version: Eclipse Persistence Services - 4.0.0.v202208221323
[8/23/22, 15:20:52:533 CDT] 0000003a eclipselink                                                  E CWWJP9992E: [eclipselink] Missing PostgreSQL10JsonPlatform from org.eclipse.persistence.pgsql module. JSON extension will not work properly. 
```

I am using bundles
```
org.eclipse.persistence:org.eclipse.persistence.core:4.0.0
org.eclipse.persistence:org.eclipse.persistence.jpa.jpql:4.0.0
org.eclipse.persistence:org.eclipse.persistence.jpa.modelgen.processor:4.0.0
org.eclipse.persistence:org.eclipse.persistence.jpa:4.0.0
```

**Comment by dazey3** [comment]
https://github.com/eclipse-ee4j/eclipselink/blob/b8b009d799389faf74b9c8a5d96f58cf6884d54b/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java#L369

https://github.com/eclipse-ee4j/eclipselink/blob/b8b009d799389faf74b9c8a5d96f58cf6884d54b/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQL10Platform.java#L61-L73

It looks like `org.eclipse.persistence.platform.database.PostgreSQL10Platform` (which is in `org.eclipse.persistence.core`) is requiring `org.eclipse.persistence.pgsql` for PostgreSQL.

Could `org.eclipse.persistence.platform.database.PostgreSQL10Platform` instead check for `org.eclipse.persistence.json`? If `org.eclipse.persistence.json` exists, but it isn't `PostgreSQL10JsonPlatform`, then maybe it is `SessionLog.SEVERE`. But without `org.eclipse.persistence.json`, I think it should be `SessionLog.INFO`

**Comment by lukasj** [comment]
Since the dependency on `org.eclipse.persistence:org.eclipse.persistence.pgsql` is supposed to be optional, the level should be either CONFIG or FINE (INFO would probably be fine too) but definitely not SEVERE. Just noticed that the extension itself does not comply with the requirements for running on JPMS... @Tomas-Kraus, would you mind to fix this?

**Comment by Tomas-Kraus** [comment]
Yes, I can do something with log level here. :)

**Comment by dazey3** [comment]
@Tomas-Kraus 

It seems like you are trying to produce a message for the scenario where module `org.eclipse.persistence.pgsql` is not being loaded, but the user is using PostgreSQL + `org.eclipse.persistence.json`. Is that correct?

Except, this error check in `org.eclipse.persistence.platform.database.PostgreSQL10Platform` is also catching the scenario where neither module is being loaded.

Looking at `org.eclipse.persistence.pgsql`, it has a dependency on `org.eclipse.persistence.json`
https://github.com/eclipse-ee4j/eclipselink/blob/b8b009d799389faf74b9c8a5d96f58cf6884d54b/foundation/org.eclipse.persistence.pgsql/pom.xml#L33-L41

That makes sense, but this error message seems to be forcing a dependency of `org.eclipse.persistence.pgsql` on `org.eclipse.persistence.json`, right? Granted that is perhaps a weak dependency because it's only required for Postgres... but it does seem like a runtime dependency. Should we be looking at adding `org.eclipse.persistence.pgsql` to `org.eclipse.persistence.json` dependencies (which would be a circular dependency)?

It just seems odd that we have this programmatic enforcement of `org.eclipse.persistence.json` depending on `org.eclipse.persistence.pgsql`. I understand why `org.eclipse.persistence.pgsql` exists, but I'm wondering if there is a different way to organize this. Or perhaps this is the only way to make it work.

**Comment by Tomas-Kraus** [comment]
Postgres 10 DB Platform is in core so it should work without `org.eclipse.persistence.pgsql`/`json` too. But it uses few features from org.eclipse.persistence.pgsql when they are available:
1. [setParameterValueInDatabaseCall](https://github.com/eclipse-ee4j/eclipselink/blob/b8b009d799389faf74b9c8a5d96f58cf6884d54b/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQL10Platform.java#L113) uderstands `PGobject` instance 
2. Postgress DB JSON support is added.

And yes, there is hard dependency `org.eclipse.persistence.pgsql` -> `org.eclipse.persistence.json`, because `org.eclipse.persistence.pgsql` was implemented to add JSON specific features to Postgres 10 DB Platform as optional dependency trough SPI.

I'll just change log level to `CONFIG` and also rewrite message to be less aggressive.

**Comment by dazey3** [comment]
> When user tries to use those JSON specific features without org.eclipse.persistence.pgsql/json, it will not work

I think that's where I am getting confused. The error log is not being produced when using "those JSON specific features". The error is being logged for just using `PostgreSQL10Platform` because it's on the constructor.

**Comment by Tomas-Kraus** [comment]
It's PgSQL specific case. But I'll changed level of this message to FINE so there won't be any message.
