### ISSUE TITLE
JPA Criteria API: Empty IN Statement leads to SQL-Error

### ISSUE THREAD

**Issue by laeubi** [eclipse-ee4j/eclipselink#847]
Transfer of https://bugs.eclipse.org/bugs/show_bug.cgi?id=415771

**Comment by dfex55** [comment]
The same SQL error appears using jpql and setting an empty list as a parameter.

Example:

jpql query:
"select e from Example e where e.id in (:myIds)"

Java Code:
<typedQuery>.setParameter("myIds", new ArrayList<>()).getResultList();

Is this intended? Could this be fixed in a similar way (maybe as part of this issue)? Or should there be a separate issue?

**Comment by rfelcman** [comment]
> The same SQL error appears using jpql and setting an empty list as a parameter.
> 
> Example:
> 
> jpql query:
> "select e from Example e where e.id in (:myIds)"
> 
> Java Code:
> .setParameter("myIds", new ArrayList<>()).getResultList();
> 
> Is this intended? Could this be fixed in a similar way (maybe as part of this issue)? Or should there be a separate issue?

Sorry but JPQL queries execution is different. It more "straight" to database. These queries are not build from methods like `CriteriaBuilder` way. In this case it's up to user to pass there correct parameter value.

**Comment by laeubi** [comment]
> Sorry but JPQL queries execution is different.

Can you please reopen? the original bugreport was acout JPA Criteria Queriesm JPQL was brought in by @dfex55 in the discussion...

**Comment by laeubi** [comment]
Okay I missed that there are some action already so @rfelcman is this actually fixed (for JPA Criteria?)
